# Generated by Django 4.0.4 on 2022-04-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='music.like'),
            preserve_default=False,
        ),
    ]
