# Generated by Django 4.0.4 on 2022-04-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_art',
            field=models.CharField(default='Image coming soon', max_length=1000),
            preserve_default=False,
        ),
    ]
